/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Swee Zhi Jin
 */
package Admin;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class RegisterLecturer extends javax.swing.JFrame {
    private final Admin admin;
    private final String adminId;
    private Admin_Lecturer admin_lecturer;
    private DefaultComboBoxModel<String> adminModel;
    private DefaultComboBoxModel<String> lecturerModel;
    private javax.swing.JFrame previousFrame;

    /**
     * Creates new form RegisterLecturer
     */
    public RegisterLecturer(Admin admin, String lecturerID, String name, String password, String email, String phoneNumber, String department, String role, boolean isEditing, javax.swing.JFrame previousFrame) {
        initComponents();
        this.admin = admin;
        this.adminId = admin.getID(); // Get adminId from admin object
        this.previousFrame = previousFrame;
        
        lecturerIDTxt.setText(lecturerID);
        lecturerNameTxt.setText(name);
        lecturerPasswordTxt.setText(password);
        lecturerEmailTxt.setText(email);
        lecturerPhoneNumTxt.setText(phoneNumber);
        lecturerDepartmentCmb.setSelectedItem(department);
        
        lecturerModel = new DefaultComboBoxModel<>(new String[] {"Lecturer", "Project Manager"});
        adminModel = new DefaultComboBoxModel<>(new String[] {"Admin"});
        if (role.equals("Admin")) {
            lecturerRoleCmb.setModel(adminModel);
            lecturerDepartmentCmb.setEnabled(false);
        } else if (role.equals("Lecturer")) {
            lecturerRoleCmb.setModel(lecturerModel);
        }
        lecturerRoleCmb.setSelectedItem(role);
        
        // Change button text and action based on isEditing flag
        if (isEditing) {
            titleLbl.setText("Update Lecturer");
            lecturerIDTxt.setEditable(false); // Set the text field to be uneditable
            registerLecturerBtn.setText("Save Changes");
            registerLecturerBtn.addActionListener(e -> updateLecturer());
        } else {
            if (role.equals("Admin")) {
                titleLbl.setText("Register Admin");
                lecturerIDLbl.setText("Admin ID");
                registerLecturerBtn.setText("Add Admin");
                registerLecturerBtn.addActionListener(e -> addLecturer());
            } else {
                titleLbl.setText("Register Lecturer");
                registerLecturerBtn.setText("Add Lecturer");
                registerLecturerBtn.addActionListener(e -> addLecturer());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lecturerDepartmentCmb = new javax.swing.JComboBox<>();
        registerLecturerBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        lecturerNameTxt = new javax.swing.JTextField();
        phoneNumLbl = new javax.swing.JLabel();
        lecturerPhoneNumTxt = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        departmentLbl = new javax.swing.JLabel();
        roleLbl = new javax.swing.JLabel();
        lecturerPasswordTxt = new javax.swing.JTextField();
        lecturerEmailTxt = new javax.swing.JTextField();
        lecturerIDLbl = new javax.swing.JLabel();
        lecturerIDTxt = new javax.swing.JTextField();
        lecturerRoleCmb = new javax.swing.JComboBox<>();
        closeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lecturerDepartmentCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Computing", "Accounting", "Engineering", "Business", "Media" }));
        lecturerDepartmentCmb.setToolTipText("");
        lecturerDepartmentCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerDepartmentCmbActionPerformed(evt);
            }
        });

        registerLecturerBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        registerLecturerBtn.setText("Register Lecturer");
        registerLecturerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerLecturerBtnActionPerformed(evt);
            }
        });

        nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameLbl.setText("Name : ");

        phoneNumLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phoneNumLbl.setText("Phone Number : ");

        titleLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Register Lecturer");

        passwordLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordLbl.setText("Password : ");

        emailLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailLbl.setText("Email : ");

        departmentLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        departmentLbl.setText("Department : ");

        roleLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roleLbl.setText("Role : ");

        lecturerEmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerEmailTxtActionPerformed(evt);
            }
        });

        lecturerIDLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lecturerIDLbl.setText("Lecturer ID : ");

        lecturerRoleCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecturer", "Project Manager" }));
        lecturerRoleCmb.setToolTipText("");
        lecturerRoleCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerRoleCmbActionPerformed(evt);
            }
        });

        closeBtn.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        closeBtn.setText("Close");
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lecturerIDLbl)
                            .addComponent(departmentLbl)
                            .addComponent(roleLbl)
                            .addComponent(passwordLbl)
                            .addComponent(nameLbl)
                            .addComponent(phoneNumLbl)
                            .addComponent(emailLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lecturerPasswordTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lecturerEmailTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lecturerNameTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lecturerPhoneNumTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lecturerIDTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lecturerRoleCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lecturerDepartmentCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(titleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(registerLecturerBtn)
                        .addGap(89, 89, 89)
                        .addComponent(closeBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lecturerIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerPhoneNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(departmentLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lecturerDepartmentCmb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(roleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lecturerRoleCmb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerLecturerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLecturer() {
        // Get data from text fields and add new lecturer
        String staffID = lecturerIDTxt.getText();
        String name = lecturerNameTxt.getText();
        String password = lecturerPasswordTxt.getText();
        String email = lecturerEmailTxt.getText();
        String phoneNumber = lecturerPhoneNumTxt.getText();
        String department = lecturerDepartmentCmb.getSelectedItem().toString();
        String role = lecturerRoleCmb.getSelectedItem().toString();
        
        admin_lecturer = new Admin_Lecturer(adminId);
        
        // Call Admin method to register lecturer
        boolean success = (admin_lecturer.registerLecturer(staffID, name, password, email, phoneNumber, department, role)
                 && admin.registerUser(staffID, name, password, role));

        if (success && role.equals("Admin")) {
            // Display success message
            JOptionPane.showMessageDialog(this, "Admin registered successfully!");
        } else if (success && role.equals("Lecturer")) {
            JOptionPane.showMessageDialog(this, "Lecturer registered successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Registration failed!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        lecturerIDTxt.setText("");
        lecturerNameTxt.setText("");
        lecturerPasswordTxt.setText("");
        lecturerEmailTxt.setText("");
        lecturerPhoneNumTxt.setText("");
        lecturerDepartmentCmb.setSelectedItem(0);
        lecturerRoleCmb.setSelectedItem(0);
        
        previousFrame.setVisible(true);
        this.dispose();
    }
    
    private void updateLecturer(){
        // Get data from text fields and update lecturer info
        String lecturerID = lecturerIDTxt.getText();
        String name = lecturerNameTxt.getText();
        String password = lecturerPasswordTxt.getText();
        String email = lecturerEmailTxt.getText();
        String phoneNumber = lecturerPhoneNumTxt.getText();
        String department = lecturerDepartmentCmb.getSelectedItem().toString();
        String role = lecturerRoleCmb.getSelectedItem().toString();
        
        admin_lecturer = new Admin_Lecturer(adminId);
        
        // Call Admin method to update lecturer details
        admin_lecturer.updateLecturer(lecturerID, name, password, email, phoneNumber, department, role);
        admin.updateUser(lecturerID, name, password, role);
        
        // Display success message or handle errors
        JOptionPane.showMessageDialog(this, "Lecturer details updated successfully!");
        
        AdminLecturer adminLecturer = new AdminLecturer(admin);
        adminLecturer.setVisible(true);
        this.dispose();
    }
    
    private void registerLecturerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLecturerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerLecturerBtnActionPerformed

    private void lecturerEmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerEmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerEmailTxtActionPerformed

    private void lecturerRoleCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerRoleCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerRoleCmbActionPerformed

    private void lecturerDepartmentCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerDepartmentCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturerDepartmentCmbActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        previousFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterLecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeBtn;
    private javax.swing.JLabel departmentLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JComboBox<String> lecturerDepartmentCmb;
    private javax.swing.JTextField lecturerEmailTxt;
    private javax.swing.JLabel lecturerIDLbl;
    private javax.swing.JTextField lecturerIDTxt;
    private javax.swing.JTextField lecturerNameTxt;
    private javax.swing.JTextField lecturerPasswordTxt;
    private javax.swing.JTextField lecturerPhoneNumTxt;
    private javax.swing.JComboBox<String> lecturerRoleCmb;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JLabel phoneNumLbl;
    private javax.swing.JButton registerLecturerBtn;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
