package Lecturer;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class StudentInfoFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentInfoFrame
     * @param studentID the StudentID to be set
     * @param projectID the ProjectID to be set
     */
    public StudentInfoFrame(String studentID, String projectID) {
        initComponents();
        findAndSetStudentInfo(studentID);
        findAndSetProjectID(projectID);
    }
    
    private void findAndSetStudentInfo(String studentID) {
        //Read textfile
        String filename = "student.txt";
        
        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            String line;
            // Loop through each line in the file
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                // Check if the current line equal the specified studentID
                if (parts[0].equals(studentID)) {
                    // Set the values of the labels
                    LabelStudentIDANS.setText(parts[0]);
                    LabelNameANS.setText(parts[1]);
                    LabelIntakeIDANS.setText(parts[3]);
                    LabelEmailANS.setText(parts[4]);
                    LabelPhoneNumberANS.setText(parts[5]);
                    break;
                }
            }
        } catch (IOException e) {
            // Catch and print IO exceptions
            e.printStackTrace();
        }
    }
    
        private void findAndSetProjectID(String projectID) {
        //Read textfile
        String filename = "Project.txt";
        
        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            String line;
            // Loop through each line in the file
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                // Check if the current line equal the specified projectID
                if (parts[0].equals(projectID)) {
                    // Set the values of the labels
                    LabelProjectIDANS.setText(parts[0]);
                    LabelCategoryANS.setText(parts[1]);
                    LabelIndividualGroupANS.setText(parts[2]);
                    break;
                }
            }
        } catch (IOException e) {
            // Catch and print IO exceptions
            e.printStackTrace();
        }
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelTitle = new javax.swing.JLabel();
        ButtonBack = new javax.swing.JButton();
        LabelIntakeID = new javax.swing.JLabel();
        LabelProjectIDANS = new javax.swing.JLabel();
        LabelStudentID = new javax.swing.JLabel();
        LabelProjectID = new javax.swing.JLabel();
        LabelName = new javax.swing.JLabel();
        LabelStudentIDANS = new javax.swing.JLabel();
        LabelNameANS = new javax.swing.JLabel();
        LabelIntakeIDANS = new javax.swing.JLabel();
        LabelEmail = new javax.swing.JLabel();
        LabelEmailANS = new javax.swing.JLabel();
        LabelPhoneNumberANS = new javax.swing.JLabel();
        LabelPhoneNumber = new javax.swing.JLabel();
        LabelIndividualGroup = new javax.swing.JLabel();
        LabelCategoryANS = new javax.swing.JLabel();
        LabelCategory = new javax.swing.JLabel();
        LabelIndividualGroupANS = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitle.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        LabelTitle.setText("StudentInfo");

        ButtonBack.setText("Back");
        ButtonBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBackActionPerformed(evt);
            }
        });

        LabelIntakeID.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelIntakeID.setText("IntakeID:");

        LabelProjectIDANS.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelProjectIDANS.setText("ProjectID");

        LabelStudentID.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelStudentID.setText("StudentID:");

        LabelProjectID.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelProjectID.setText("ProjectID:");

        LabelName.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelName.setText("Name:");

        LabelStudentIDANS.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelStudentIDANS.setText("StudentID");

        LabelNameANS.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelNameANS.setText("Name");

        LabelIntakeIDANS.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelIntakeIDANS.setText("IntakeID");

        LabelEmail.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelEmail.setText("Email:");

        LabelEmailANS.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelEmailANS.setText("Email");

        LabelPhoneNumberANS.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelPhoneNumberANS.setText("PhoneNumber");

        LabelPhoneNumber.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelPhoneNumber.setText("PhoneNumber:");

        LabelIndividualGroup.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelIndividualGroup.setText("Individual / Group:");

        LabelCategoryANS.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelCategoryANS.setText("Category");

        LabelCategory.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelCategory.setText("Category:");

        LabelIndividualGroupANS.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        LabelIndividualGroupANS.setText("Individual / Group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTitle)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelIndividualGroup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelIndividualGroupANS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelIntakeID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelIntakeIDANS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelStudentID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelStudentIDANS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelPhoneNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelPhoneNumberANS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelEmailANS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelProjectID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelProjectIDANS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelCategory)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelCategoryANS))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelNameANS)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelStudentID)
                    .addComponent(LabelStudentIDANS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelName)
                    .addComponent(LabelNameANS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIntakeID)
                    .addComponent(LabelIntakeIDANS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmail)
                    .addComponent(LabelEmailANS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPhoneNumber)
                    .addComponent(LabelPhoneNumberANS))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelProjectID)
                    .addComponent(LabelProjectIDANS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCategory)
                    .addComponent(LabelCategoryANS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIndividualGroup)
                    .addComponent(LabelIndividualGroupANS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBackActionPerformed
        // TODO add your handling code here:
        // Dispose of the current frame
        dispose();
        //Open another frame
//        LectureFrame lectureFrame = new LectureFrame();
//        lectureFrame.setVisible(true);
    }//GEN-LAST:event_ButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInfoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentInfoFrame("StudentID","ProjectID").setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBack;
    private javax.swing.JLabel LabelCategory;
    private javax.swing.JLabel LabelCategoryANS;
    private javax.swing.JLabel LabelEmail;
    private javax.swing.JLabel LabelEmailANS;
    private javax.swing.JLabel LabelIndividualGroup;
    private javax.swing.JLabel LabelIndividualGroupANS;
    private javax.swing.JLabel LabelIntakeID;
    private javax.swing.JLabel LabelIntakeIDANS;
    private javax.swing.JLabel LabelName;
    private javax.swing.JLabel LabelNameANS;
    private javax.swing.JLabel LabelPhoneNumber;
    private javax.swing.JLabel LabelPhoneNumberANS;
    private javax.swing.JLabel LabelProjectID;
    private javax.swing.JLabel LabelProjectIDANS;
    private javax.swing.JLabel LabelStudentID;
    private javax.swing.JLabel LabelStudentIDANS;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
